authors = ["ScottPJones <scottjones@alum.mit.edu>"]
desc = "MurmurHash3 implementation in pure Julia"
keywords = ["Strings", "Hashing"]
license = "MIT"
name = "MurmurHash3"
uuid = "b10b62ed-fbae-5ea5-b934-abaf0477b71d"

[deps]
Pkg  = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
