authors = ["ScottPJones <scottjones@alum.mit.edu>"]
desc = "MurmurHash3 implementation in pure Julia"
keywords = ["Strings", "Hashing"]
license = "MIT"
name = "MurmurHash3"
uuid = "f0d41675-b40b-4ac0-9c24-1938651d8492"

[deps]
Pkg  = "fe1c5a76-5840-53d2-82f9-288dd83ce2ce"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
